:PROPERTIES:
:ID:       799c5a72-2e8f-48a3-a22d-6657b9d1c05d
:END:
#+title: Apply search tools and techniques for your digital library
#+date: "2020-06-27 16:21:47 +08:00"
#+date_modified: "2021-07-11 20:10:35 +08:00"
#+language: en
#+tags: personal-info-management


With digital files comes digital tools (and some techniques) to help us in searching for our notes.
These can vary from complex technologies to simple format-agnostic techniques that can make querying files with specific information to be a breeze. [fn:: If you want to maintain your personal digital library, make sure to document how you work.
Your future self will thank you later.]

In order to search effectively, you need to consider [[id:ea263f6f-fa8e-4e6d-a585-d30d493d1e3c][Desktop search engines]] that can also search [[id:ccb3bc14-a801-4ed0-b066-50b1bcd853aa][File metadata]].
This is also great if you consider [[id:66337935-420c-40e6-81a6-f74ab0965ed5][Maintaining a digital library]] for yourself.

For text files, you can consider [[id:c15325eb-4506-449c-b8dd-300801f53adc][A good tagging system for files for reducing information overload]]  that also consider publication to the public (e.g., digital gardens, static site generators).

Creating a search interface is one thing;
having the ability for retrieving resources is a must especially if your collection is getting big.
Like real-life libraries, you need a system to refer to certain resources easily while adding new ones.
What is the use of a collection if it's not being used?
It is just like my unread collection of digital books I've sworn to read.

Applying well-thought searching practices and precautions reduces [[https://en.wikipedia.org/wiki/Information_overload][information overload]] especially when looking for broad domain topics.
This is useful for researching technical topics where domain-specific topics are often present and you need a way to refer back to wider subjects;
much more so if you want to create [[id:6eeb7a24-b662-46d6-9ece-00a5028ff4d8][Reproducible research]].




* References

[[https://www.fun-mooc.fr/courses/course-v1:inria+41016+self-paced/info][Reproducible research: principles for transparent science]], Module 1: Lab books and notebooks, Section 5: Finding one's way with tags and desktop search application, retrieved as of June 2020 (2020-06-24)
