:PROPERTIES:
:ID:       05a39f96-fb1c-4d71-9be1-fc4c2e251e8f
:END:
#+title: Start small and improve later
#+date: "2021-05-05 18:06:29 +08:00"
#+date_modified: "2021-07-22 14:31:32 +08:00"
#+language: en


This is a very simple advice applicable on lots of places.

- In speedrunning, when starting to learn the mechanics of the game, you may want to finish a whole run no matter how bad it is to get the bigger picture.
  This way, you'll know what techniques and tricks you find difficult and improve on it immediately.

- When [[id:4b33103b-7f64-4b51-8f03-cac06d4001bb][Programming]], you can start with solving one coding problem until you're now comfortable to take two.
  Then, with a couple of problems, you're now comfortable to take three and so on.

- In [[id:cd7e8120-6953-44a6-9004-111f86ac52dc][Illustration]], one often starts with a sketch with rough shapes and outlines.
  The details may then change in the later phases of the sketch.
  This can make immediate improvements especially when you found out the outcome does not fit with what you've visualized.

- In [[id:af0ccefe-c671-47bf-94f7-62243c805745][Skill-building]], you start from the basic concepts.
  This is to build a foundation for complex topics and flexibility you need to create a solution.

- In [[id:815b2beb-40a0-4e79-9097-5b688189ad5b][Writing]], you often start with the outlines of the article or a story.
  You then fill the details for the point or scenario you're writing.

The point is to reach bigger advancements must come from somewhere even in the smallest amounts.
[[id:adefcd38-46a8-4c9c-b609-9d3393b074d0][Consistency over time creates more progress]].
Once you get comfortable with the task you're supposed to do, you're now getting bigger results than you anticipated from doing one big task in a day.
There is always on opportunity to improve things.

On the other hand, this gradual progression also presents itself on other areas.

- Video games with well-designed tutorials introducing you to the game slowly building up to more complex levels.
- Applications with well-designed tours [fn:: Also known as an out-of-box experience.] where it present limited aspects of an app enabling you to combine them and create more complex pieces.
- Programming documentation often involves the simplest examples then letting you figure out how the rest of the stuff works.
