:PROPERTIES:
:ID:       efe742a6-7d23-49bb-81b7-94c0437af720
:END:
#+title: Android free and open source apps
#+date: "2021-06-19 01:02:29 +08:00"
#+date_modified: "2021-08-08 20:03:37 +08:00"
#+language: en


Android is not much of an open ecosystem despite the kernel is [[https://source.android.com/][open source]] due to the most of the phones distributed with the manufacturer's modification.

There are solutions into this such as Android custom ROMs and privacy-oriented mobile operating systems such as [[https://source.android.com/][postmarketOS]] and [[https://lineageos.org/][LineageOS]] but that is not the topic.
However, they are often not ready and/or widely supported.
We may as well take advantage of the Android improvements and features by creating free and open source apps on it.

Here is my personal list of noteworthy Android apps:

- [[https://f-droid.org/en/packages/][F-Droid]] is a privacy-oriented app store for Android.
  It builds all of the hosted apps from scratch for privacy and security sake of fully [[id:fe9e21bc-3b38-4d0f-a785-253248a38ed7][Reproducible builds]].

- [[https://newpipe.net/][Newpipe]] is a YouTube frontend alternative to the official YouTube mobile app.
  Most of the features you would find in the app doesn't require logins such as subscription and playlist management.
  Also can import and export user data from the app.

- [[https://f-droid.org/packages/com.apps.adrcotfas.goodtime/][Goodtime]] is a Pomodoro timer.
  You can also export your sessions to data.

- [[https://f-droid.org/packages/mn.tck.semitone/][Semitone]] is a piano app for musicians.
  This is what I use for studying music theory.

- [[https://kisslauncher.com/][KISS Launcher]] is a self-titled simple launcher with a homepage and a search interface.
  Supports pinning apps and adding app widgets in the homepage.
