:PROPERTIES:
:ID:       6e8912b3-1687-47dc-9d85-269ea6372317
:END:
#+title: Anatomy of the brain
#+date: 2021-07-21 15:01:06 +08:00
#+date_modified: 2021-07-21 15:01:23 +08:00
#+language: en


Remebering from our basic biology lessons, we know that the brain contains *neurons that store information*.
These information can be connected together with *synapses that represents a web of thoughts* from the process of [[id:1e135aee-0464-4756-9f55-bbf12afe8254][Chunking]] information together.
It shows why [[id:9f1f35dd-7cf9-4f47-a9a9-b647e5daa2af][We are more associative than structured]];
indeed, we are very skilled in linking and jumping between ideas.
You may have moments of suddenly remembering that you forgot to bring something while in the middle of your nap or a Eureka! moment where you suddenly understand why the quadratic formula makes sense.

The memory can be compared to the muscles as it strengthens the more you use and decays the more you neglect.
In order for this to work, however, you need to set some time for the neural structure to harden first.
This is why cramming doesn't work and [[id:063dfd73-dbf5-437b-b6f1-d7aeca196f31][Spaced repetition]] is often considered a better method.
