:PROPERTIES:
:ID:       0dbfee88-cdce-48d1-9a10-23fc12d9bcd5
:END:
#+title: Refer to advanced resources when skill-building for a solid short-term goal
#+date: "2020-07-06 03:47:52 +08:00"
#+date_modified: "2021-06-17 10:45:10 +08:00"
#+language: en


When starting out to build a skill like programming, 3D modelling, digital art, or cooking, you can look first for expert-created resources.
For example, when starting out to 3D model, you can look for speedsculpting videos or a competition that involves many talented people in the industry.
In programming, you could look for devlogs, highly advanced competitions, fairly popular software projects, or a live coding session.
You can then store the expert resources and [[id:66337935-420c-40e6-81a6-f74ab0965ed5][Maintain your own digital library]] for future references.

The purpose of this is twofold: to serve as a solid short-term goal (as indicated by the title) and to create inspirations for your future projects.
If you [[id:fdf9e3eb-02c5-47a6-b586-e71a5c92d01a][Look for live sessions as another form of examples]], the inspirations are especially great as you watch the actual process unfold.

Of course, this does not entirely replace looking out for beginner-friendly resources and communities as an entryway.
In fact, it is a bad idea to start learning with the advanced resources.

Beware, this could lead into actively consuming just the resources without the practice.
Remember, [[id:114b7874-6a20-49c8-be2c-46970c7110dc][Information is only acquired when you try to make sense of it]].
[[id:6b0e6b75-410f-42a3-8921-bcc4589b2d2a][Collecting information only feels like progress]].
To prevent this passive consuming, [[id:92a10fe2-f4d1-4e5e-b5f4-3779db13a2e5][Create roadmaps to stay on track]].
