:PROPERTIES:
:ID:       ea263f6f-fa8e-4e6d-a585-d30d493d1e3c
:END:
#+title: Add a desktop search engine for your digital library
#+date: "2020-04-15 20:41:51 +08:00"
#+date_modified: "2021-05-13 14:15:39 +08:00"
#+language: en


Desktop search engines adds a crucial thing for [[id:66337935-420c-40e6-81a6-f74ab0965ed5][Maintaining your own digital library]]: retrievability.
With the ability to search and retrieve for information scattered throughout our files, we can then quickly connect and add information without much burden.

An ideal desktop search engine should have the following things:

- Features both a graphics user interface (GUI) and a command-line interface (CLI).
- Accepts not only plain-text files but other file formats such as images, videos, and audio.
- Quickly searches through text and even [[id:ccb3bc14-a801-4ed0-b066-50b1bcd853aa][File metadata]] for binary files.
- Invites integration (and extension) with an API allowing for more control and features.
- Highlights searching with a query language that is both simple and powerful.

With a cursory search, I found [[id:253c59a3-f5ba-4d77-b535-7447a512945d][Recoll]] that fits the bill with the added bonus of being a cross-platform tool and easily configurable.
