#+TITLE: Maintain your own digital library
#+AUTHOR: "Gabriel Arazas"
#+EMAIL: "foo.dogsquared@gmail.com"
#+DATE: "2020-04-14 18:28:55+08:00"
#+DATE_MODIFIED: "2020-09-09 05:09:20+08:00"
#+LANGUAGE: en
#+OPTIONS: toc:t
#+PROPERTY: header-args  :exports both


Having your own digital library can be one of the most valuable thing for your life.
It is flexible in purpose: you can use it as a personal knowledge base, digital novelties collection, and/or project repository.

A digital library should have the following features:

- Easy to maintain (e.g., modifying [[file:2020-04-13-17-32-27.org][File metadata]], adding more digital objects) which is the top priority.
- Catalog the files using open standardized tools and specifications if available.
- Provide an easy and reliable search interface with rich metadata.

Instituition libraries such as Internet Archive and ArXiv are the go-to examples for a long sustaining digital library.
On the other hand, personal digital libraries are basically personal information management systems where your resources are stored: documents, notes, references, and media files.

I have been thinking of creating a digital library for myself.
These are the tools I've been using for my experiment:

- Zotero as my reference management library.
- Exiftool for annotating my files with metadata.
- Recoll as the search interface.
- Org-Mode with org-roam as my personal wiki/knowledge base.

There are a couple of minor things such as Buku as my bookmarks manager, lf as a file explorer, mpv for multimedia, and Firefox as my web browser.

The digital library does not have to be integrated as the established libraries, you just have to loosely connect a system with each of the components of your library.
My digital library are fragmented with each component located in its own directory (e.g., Zotero data directory is in ~$HOME/Documents/references~, books and documents are at ~$HOME/Documents/books~, wiki at ~$HOME/writings/wiki~) but it is a non-problem for me and it is easy to solve if it's a problem.




* Related resources

- https://github.com/DSpace/DSpace
- https://ieeexplore.ieee.org/Xplore/home.jsp
- https://unpaywall.org/
- https://www.loc.gov/catworkshop/courses/metadatastandards/pdf/MSTraineeManual.pdf

For more digital library examples, see https://en.wikipedia.org/wiki/List_of_digital_library_projects.
