#+title: Common problems with software packaging
#+date: "2020-09-13 19:42:06 +08:00"
#+date_modified: "2021-04-24 01:46:13 +08:00"
#+language: en


Several of the problems I've encountered while practicing packaging (aside from unfamiliarity, of course) is of the following:

- How distinct each project could be in case they don't follow the standard.
  Not really a problem as most of them has documentation available for it.

- Some of them are built with assumptions or a preset environment which may need patching.

- Sparse documentation for building the software.
  Some of them are particularly intuitive but in case it is lacking, you're on your own (unless they're open for discussions and pull requests).

The process of software packaging might vary but in my case, it is pretty straightforward with [[file:2020-09-04-16-07-47.org][Nix package manager]] (though not-so-great with its [[https://nixos.org/learn.html][documentation]]) and even more so with [[file:2020-08-19-08-21-44.org][GNU Guix]] with its [[https://guix.gnu.org/help][open communication and well-made documentation]].
