#+TITLE: Information literacy
#+AUTHOR: "Gabriel Arazas"
#+EMAIL: "foo.dogsquared@gmail.com"
#+DATE: "2020-07-01 23:19:07 +08:00"
#+DATE_MODIFIED: "2020-09-09 05:09:40 +08:00"
#+LANGUAGE: en
#+OPTIONS: toc:t
#+PROPERTY: header-args  :exports both


Information literacy is defined as the ability to search information, sort the results, verify for legitimacy, and share the information effectively.
It is one of the most important universal skills as internet became popular as a method of distributing information causing to often deal with the torrential amount of information.

There are many ways to improve our information literacy including usage of various effective online searching, writing [[file:2020-06-25-13-12-09.org][Fleeting notes]] for a quick capture system, and finally evaluating your search results with [[file:2020-05-07-21-53-21.org][Evergreen notes]].
For an increased output, you can [[file:2020-04-14-18-28-55.org][Maintain your own digital library]] and [[file:2020-06-27-16-21-47.org][Apply search tools and techniques for your digital library]] where you can store your results and freely retrieve them whenever you wish.

Having a sharp information literacy does not only mainly seen in technical fields like in research and academia (e.g., literature reviews, peer reviews) but also on everyday life as well.
In fact, all of us practice it in some way.
We use information literacy skills when we research for the laptop that brings the best value to our limited budget, verifying if the online seller is legitimate, or sharing certain information on our social media.
