:PROPERTIES:
:ID:       f0d0198c-b523-4d71-a13c-0c578dfac3ef
:END:
#+title: Information literacy
#+date: "2020-07-01 23:19:07 +08:00"
#+date_modified: "2021-05-09 18:02:12 +08:00"
#+language: en
#+tags: personal-info-management


The ability to search information, sort the results, verify for legitimacy, and share the information effectively.
A very useful skill nowadays with the torrential amount of information.

There are many ways to improve our information literacy including usage of various effective online searching, capture relevant output, and finally evaluating your search results.

Having a sharp information literacy does not only mainly seen in technical fields like in research and academia (e.g., literature reviews, peer reviews) but also on everyday life as well.
In fact, all of us practice it in some way.
We use information literacy skills when we research for the laptop that brings the best value to our limited budget, verifying if the online seller is legitimate, or sharing certain information on our social media.




* How to practice this skill?

- [[id:9a11ef31-b2a7-43a9-a7a9-48f191838c6e][Prefer referencing over remembering]] — that is, learn to create effective narrow searches.
- [[id:0dbfee88-cdce-48d1-9a10-23fc12d9bcd5][Refer to advanced resources when skill-building for a solid short-term goal]] for an effective headstart.
- Learn effective [[id:88f2256a-3359-4d10-92a3-9273cabce414][Personal information management]] to capture relevant information and save time from searching the result.
