#+title: File metadata
#+date: "2020-04-13 17:32:27 +08:00"
#+date_modified: "2021-05-02 02:11:01 +08:00"
#+language: en


File metadata is one of the most subtle requirements in [[file:2020-04-23-23-21-47.org][Personal information management]].
It embeds data without relying too much on filesystem such as the file name, creation date, and modification date.

Each type of files have different ways of embedding metadata:

- Image files such as JPEG or PNG, metadata are embedded in Exchangeable image file format (EXIF).
- MP3 files have the ID3 as the de-facto standard for embedding contextual information such as the artist, album, genre, comments, and others.
- Vorbis comments is a universal format commonly found on OGG.
- HTML documents contain the ~<head>~ element to store the metadata.
- Org mode documents allow file-level properties that are functionally equivalent to embedded metadata.

There are also universal formats such as Extensible metadata platform (XMP) or Meta Information Encapsulation (MIE) available either as embedded or a separate file.

Beware about caring too much on metadata to the point of our metadata takes more space than the data themsevles.
Cautionary tales such as [[https://en.wikipedia.org/wiki/MS_Fnd_in_a_Lbry][MS Fnd in a Lbry]] have been written about it.
They are, after all, merely data on data;
if the referred data does not exist in the first place, might as well as the metadata.
