:PROPERTIES:
:ID:       583852e4-e56f-469b-89bc-9e5a832c9f04
:END:
#+title: Bidirectional links
#+date: "2020-06-28 06:19:24 +08:00"
#+date_modified: "2021-05-05 16:50:41 +08:00"
#+language: en


This feature alone allows for a different way of thinking about note-taking — notes are better to be associative than hierarchical.
The model is better suited because of how our brains work.
When learning something new, we tend to look for familiar things as a hook or a foundation, comparing it to the new concepts.
Moreover, there is a tendency for us to understand more when there's a story associated with the concept.
Whenever I remember a topic from a talk, one of the few things to come first are the examples and stories.

Compared to monodirectional links like in the web, bidirectional links have inherent social awareness: the ability to look back to linked pages.
With this feature, you can easily form a graph of pages establishing contextual relationships between them.
This is a feature I always like to see especially for technical websites such as [[https://encyclopediaofmath.org/][Encyclopedia of Mathematics]].

That said, bidirectional linking is not a silver bullet.
If this is implemented on the web today, it would cause a lot of problems — spamming is one of the most common one and it can require heavy moderation.
Hence, this is more suitable for certain situations such as personal wikis and federated apps.
