:PROPERTIES:
:ID:       9b669fd4-e04e-43dd-a61e-81dea5ec0764
:END:
#+title: Deliberate practice
#+date: "2020-07-06 23:55:47 +08:00"
#+date_modified: "2021-05-20 20:34:52 +08:00"
#+language: en


Unlike regular practice that involves mindless repetitions, deliberate practice involves purposeful sessions.
Each session aims to improve performance and increase the skill ceiling of the practitioner.
That is each session to be effective, [[id:1a6187c9-6c79-4378-bf8d-935c8a3d9167][When learning a new skill, begin with a specific end-goal to create a solid starting point]].

To put it simply, deliberate practice involves getting out of comfort zone and enforces discipline.
For example, trying yourself to solve some hard mathematical problems or competitive programming for the first time with a mentor.

You can also [[id:0dbfee88-cdce-48d1-9a10-23fc12d9bcd5][Refer to advanced resources when skill-building for a solid short-term goal]].
With it, identify the top performers in the field and try to make a conclusion on how do they get so far.

You can also put yourself in their shoes as a newcomer.
Try to tackle a difficult problem, [[roam:Diving head-first with a difficult problem is a good indicator of progress]].
Beware, [[roam:Diving head-first into a difficult problem makes a bad start]].
