#+title: Apply search tools and techniques for your digital library
#+author: "Gabriel Arazas"
#+email: "foo.dogsquared@gmail.com"
#+date: "2020-06-27 16:21:47 +08:00"
#+date_modified: "2021-04-05 15:39:17 +08:00"
#+language: en
#+tags: personal-info-management


With digital files comes digital tools (and some techniques) to help us in searching for our notes.
These can vary from complex technologies to simple format-agnostic techniques that can make querying files with specific information to be a breeze.
[fn:: If you want to maintain your personal digital library, make sure to document how you work.
Your future self will thank you later.]

In order to search effectively, you need to consider [[file:2020-04-15-20-41-51.org][Desktop search engines]] that can also search [[file:2020-04-13-17-32-27.org][File metadata]].
This is also great if you consider [[file:2020-04-14-18-28-55.org][Maintaining a digital library]] for yourself.

For text files, you can consider [[file:2020-06-24-14-33-42.org][A good tagging system for files for reducing information overload]]  that also consider publication to the public (e.g., digital gardens, static site generators).

Creating a search interface is one thing;
having the ability for retrieving resources is a must especially if your collection is getting big.
Like real-life libraries, you need a system to refer to certain resources easily while adding new ones.
What is the use of a collection if it's not being used?
It is just like my unread collection of digital books I've sworn to read.

Applying well-thought searching practices and precautions reduces [[https://en.wikipedia.org/wiki/Information_overload][information overload]] especially when looking for broad domain topics.
This is useful for researching technical topics where domain-specific topics are often present and you need a way to refer back to wider subjects;
much more so if you want to create [[file:2020-04-12-11-20-53.org][Reproducible research]].




* References

[[https://www.fun-mooc.fr/courses/course-v1:inria+41016+self-paced/info][Reproducible research: principles for transparent science]], Module 1: Lab books and notebooks, Section 5: Finding one's way with tags and desktop search application, retrieved as of June 2020 (2020-06-24)
