#+TITLE: When learning a new skill, begin with a specific end-goal to create a solid starting point
#+AUTHOR: "Gabriel Arazas"
#+EMAIL: "foo.dogsquared@gmail.com"
#+DATE: "2020-07-08 22:42:47 +08:00"
#+DATE_MODIFIED: "2020-12-05 21:43:46 +08:00"
#+LANGUAGE: en
#+OPTIONS: toc:t
#+PROPERTY: header-args  :exports both


This top-bottom learning approach (i.e., specific to general topics) is often used by self-learners.
It usually involves something like wanting to create a 2.5D fighting game rivalling [[https://en.wikipedia.org/wiki/Arc_System_Works][Arc System Works]], a gorgeous anime-inspired illustration, [[https://www.youtube.com/watch?v=TF9I1GxNdJQ][a flashy short animation]], or [[https://www.youtube.com/watch?v=ZwR0zFe57Y4][a cool-looking demoscene]].

Most of the time, the process of skill acquisition happens similarly to the following workflow with varying effectiveness.
(As obvious as it seems, simply laying it out can add some perspectives [at least to me].)

- Document your specific example (e.g., a website, a drawing, a 3D scene).
  You can [[file:2020-07-06-03-47-52.org][Refer to advanced resources when skill-building for a solid short-term goal]] to clear your specific example similar to a final proof-reading before you submit your paper.
- Then, try to learn the specific example.
- For every unknown part of the example, try to understand the underlying concepts.
  If the underlying concept is not yet understood, then dig deeper into understanding the underlying concept of that underlying concept ad infinitum.
- With the tree of to-be-understood underlying concepts, take a peek between each underlying concepts  of various depths until you can easily see the connections between them.
- Work your way up the knowledge tree you've just created until you can reproduce/create the example with your newfound hierarchical knowledge.

The gist of the above list is to create your roadmap.
That way, it doesn't lead you into aimlessly learning stuff and get you efficient in upping your skill level.

The general idea is having a specific example aids you in creating an outline of the related general concepts which in turn aids you into learning what you want to learn.
You can easily see what gaps of knowledge should you fill to fully understand a specific concept whether it is simple, technical, or complex.
I recommend to record the outline in a plain-text [[file:2020-04-15-14-35-55.org][Note-taking]] tool like [[file:2020-04-20-16-51-40.org][Org-mode]], Asciidoctor, or Markdown.

Not every attempts of skill acquisition is suitable with this workflow with some skills need more experiments than others.
The above workflow is more suitable to acquire advanced skills than entry-level skills where aiming for a perfect first try is (obviously) not an attractive goal.
