#+TITLE: Make personal backups effectively with the 3-2-1 rule
#+AUTHOR: "Gabriel Arazas"
#+EMAIL: "foo.dogsquared@gmail.com"
#+DATE: "2020-12-10 20:49:03 +08:00"
#+DATE_MODIFIED: "2020-12-11 00:48:19 +08:00"
#+LANGUAGE: en
#+OPTIONS: toc:t
#+PROPERTY: header-args  :exports both


If you want to start good backup practices, the 3-2-1 rule is a good starting point.
The 3-2-1 rule states that your backup should have 3 copies of your data stored in 2 media (e.g., internal hard drive, external storage) with at least 1 of them stored offsite of your computer (e.g., remote location, cloud service).
This is especially important for your personal data such as your digital library (see [[file:2020-04-14-18-28-55.org][Maintain your own digital library]]) for example.

Making at least three copies of your data is a good way of mitigating against certain things like hardware failure, data corruption, and theft.

Maintaining those copies in different media (e.g., storage drives, email accounts) is easier said than done.

- Firstly, having multiple copies on the same medium doesn't count.
  If the data corrupted, you'll also have the other copy corrupted.
  If the online storage service will shut down, all of your copies are gone.

- Both of the media may not be available at the same time for one reason or another.
  You may have left your external hard drive or you may not be able to access your online storage account.

- Different requirements may apply to different mediums.
  For your local storage, all it needs to do is to copy the files to the drive.
  For others such as online storage, you may have to upload each file into your account.
  (To be fair, most online storage such as [[https://www.dropbox.com/][Dropbox]], [[https://nextcloud.com/][Nextcloud]], and [[https://www.google.com/drive/][Google Drive]] has a desktop sync option making it simple as drag-and-drop the files in a specified directory.)

For maintaining data between different media, we could easily automate them with backup tools.
For local storage, we could use [[https://www.borgbackup.org/][Borg]], [[https://rsync.samba.org/][rsync]], and [[https://www.cis.upenn.edu/~bcpierce/unison/][Unison]].
For online storage services, you can use [[https://rclone.org/][rclone]] or [[https://restic.net/][rustic]] offering support for various services such as Nextcloud, Dropbox, Google Drive, and even the local filesystem if you really want to only use one tool for the job.

If you want a stronger backup option, you can setup a dedicated machine with the appropriate software.
In the software side of things, you can install appropriate filesystems such as [[https://en.wikipedia.org/wiki/Network_File_System][Network File System]] (NFS) and [[https://www.gluster.org/][GlusterFS]] making it easier to create storage pools.
