:PROPERTIES:
:ID:       29ecbd86-ad97-4882-aa3f-56b5b90025d5
:END:
#+title: Create evergreen notes with a digital garden
#+date: "2020-06-04 21:32:23 +08:00"
#+date_modified: "2021-05-06 00:53:47 +08:00"
#+language: en


A digital garden is a your space for creating carefully crafted [[id:431532c3-6506-4565-b193-dbfb60eac7d6][Evergreen notes]].
Unlike a traditional blog where it concerns the final output, a digital garden cares more on the process of creating notes even if it's incomplete.
Creating one encourages to [[roam:Start small and improve later]] when it comes to your notes.
Your notes will start as a seedling, then grow as you develop more insight, and turn into a fully-developed evergreen note.

Examples of a digital garden includes [[https://notes.andymatuschak.org/][Andy Matuschak's]], [[https://maggieappleton.com/garden][Maggie Appleton's]], and [[https://www.mentalnodes.com/][Anne-Laure De Cunff's]].
[fn:: In other words, a digital garden is a properly developed wiki.]

There are many ways on creating a digital garden but here's my ideal type of a digital garden:

- Features [[id:583852e4-e56f-469b-89bc-9e5a832c9f04][Bidirectional links]] between notes as well as listing referenced notes at the bottom.
- Focuses on creating a graph of evergreen notes that can easily interrelate to one another.
- Composes of different notes of different maturity level: either an incomplete seedling of a note, a partially complete note, or a fully-developed evergreen note.
- Sports a note-taking workflow along with a publication workflow (e.g., web, PDf documents).
- Easily creates evergreen notes for technical concepts so that I can easily linked concepts common to resources (e.g., books, courses, documents).
