:PROPERTIES:
:ID:       810dc8b6-db64-4c80-a0aa-f9e6d5fa4acf
:END:
#+title: Create an inbox to store your thoughts
#+date: "2020-06-25 12:37:23 +08:00"
#+date_modified: "2021-07-05 13:40:18 +08:00"
#+language: en


While our brain is good at storing ideas, it has other things to worry about such as the random thoughts passing by each day, context switching from one task to another, and generating new ideas.
A lot of the newer thoughts have more chance to be gone in a few hours.
For this, you want to make a dedicated repository.

- The important random thoughts and the generated ideas can then be revisited for future ideas.
- Tasks can then be tracked, reminding what and/or when to be done.

Like our emails, our writing inbox should be cleaned up each time we visit our inbox.
Not all of them are going to be important so feel free to remove entries that are not in need.

If you want to store an idea for an indefinite future (e.g., a project idea, future hobbies) that you cannot surely do now, you can then create a dedicated inbox.
In practice, this is great as a starter point for [[id:3d1c0313-fa3d-4b18-b435-51d3837e3e2c][Fleeting notes]] or a reading list to [[id:66337935-420c-40e6-81a6-f74ab0965ed5][Maintain your own digital library]].

Beware, this [[id:1bdbdcfa-98f9-4d08-a0dc-ad2f1b9b9ec9][Advice shouldn't be taken literally]].
Not all thoughts are worthy of being noted, the same principle how some thoughts are not worthy to stay in your list.
Don't get into the business of unnecessary note-taking of jotting every thoughts as [[id:b62c61f1-ee12-4bd9-b59a-ec6eafe29f38][Unnecessary optimizations cripple progress]].
