#+title: Refer to advanced resources when skill-building for a solid short-term goal


When starting out to build a skill like programming, 3D modelling, digital art, or cooking, you can look first for expert-created resources.
For example, when starting out to 3D model, you can look for speedsculpting videos or a competition that involves many talented people in the industry.
In programming, you could look for devlogs, highly advanced competitions, or a live coding session.
You can then store the expert resources in your digital library (see [[file:maintaining-a-digital-library.org][Maintain your own digital library]]) for future references.

The purpose of this is twofold: to serve as a solid short-term goal (as indicated by the title) and to create inspirations for your future projects.
Other side effects include creating deliberate practice sessions and taking the stakes off to a higher start.

Of course, this does not entirely replace looking out for beginner-friendly resources and communities as an entryway (see [[file:20200701231907-information_literacy.org][Information literacy]]).
On the other hand, this prevents you from quickly entering tutorial purgatory where you'll be stuck for an indefinite amount of time.
