:PROPERTIES:
:ID:       c15325eb-4506-449c-b8dd-300801f53adc
:END:
#+title: A good tagging system for files for reducing information overload
#+date: "2020-06-24 14:33:42 +08:00"
#+date_modified: "2021-05-07 23:23:40 +08:00"
#+language: en


Stealing from [[https://www.youtube.com/watch?v=rckSVmYCH90][this talk]], the best (personal) practice for tagging include the following.

- Limiting the vocabulary into a set number.
  The author recommends to limit it to 100 but lesser is better.
- Tags should always be in plural.
- Keep tags general (e.g., =sports= instead of =bowling=, =basketball=, or =volleyball=).
- No tags should be derived from file extensions (e.g., photographs, books, documents).

In my case, this is not enough since we want tags for specific things.

- Any topic-specific should be appended as a subtag (e.g., =sports.bowling=, =sports.basketball=, =sports.volleyball=).
  If a subtag are established enough, then you may classify it as a general tag.




* References

[[https://www.fun-mooc.fr/courses/course-v1:inria+41016+self-paced/info][Reproducible research: principles for transparent science]], Module 1: Lab books and notebooks, Section 5: Finding one's way with tags and desktop search application, retrieved as of June 2020 (2020-06-24)
