:PROPERTIES:
:ID:       c422175a-5b65-4311-8cc6-11efd55364e8
:END:
#+title: Org mode
#+date: "2020-04-20 16:51:40 +08:00"
#+date_modified: "2021-05-04 20:52:08 +08:00"
#+language: en
#+tags: tools writing


At its core, [[https://orgmode.org/][Org mode]] is a [[id:88f2256a-3359-4d10-92a3-9273cabce414][Personal information management]] tool that deals with your tasks and schedules.
Nowadays, it sports a lightweight markup language and a framework that allows arbitrarily inserting output of code of various programming languages.
With these features, Org-mode is known as one of the many tools for [[id:6eeb7a24-b662-46d6-9ece-00a5028ff4d8][Reproducible research]] which also serves as a solid tool for [[id:0d2264a6-e487-4761-818a-d17d2833120f][Note-taking]] as well.

Unfortunately, a lot of the famous powers of the format is tied with [[roam:GNU Emacs][roam:GNU Emacs]].
While there is an ecosystem flourishing outside of the text editor (e.g., [[https://github.com/niklasfasching/go-org][go-org]], [[https://github.com/orgapp/orgajs][orgajs]], [[https://pandoc.org/org.html][Org mode support in Pandoc]]), the plugins inside of Emacs simply cannot be ignored.
Among other Org mode plugins inside of the Emacs ecosystem, we have [[link][org-roam]], [[https://github.com/jkitchin/org-ref][org-ref]], [[https://github.com/weirdNox/org-noter][org-noter]], [[https://orgmode.org/worg/exporters/index.html][a number of exporters]], and [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][org-babel language plugins]] (see [[id:5569a49f-c387-4da2-8f68-d8452e35ee5b][Org mode: Babel]]) that extends to more workflows.
