:PROPERTIES:
:ID:       0d2264a6-e487-4761-818a-d17d2833120f
:END:
#+title: Note-taking
#+date: "2020-04-15 14:35:55 +08:00"
#+date_modified: "2021-05-07 10:55:02 +08:00"
#+language: en


The practice of note-taking is universal — it is everybody's concern how to write their findings efficiently with the use of a [[id:88f2256a-3359-4d10-92a3-9273cabce414][Personal information management]] system.
Note-taking does not only involve the act of writing but also the act of retrieval from finding contextual relationships from two notes, separating notes into digestible chunks, and searching notes effectively.

There are different ways of note-taking.
Among the endless list of methods, popular methods include [[id:4259636e-e0e8-49e4-8210-758ec59728a3][Zettelkasten]], [[id:24b5e144-dda4-482c-9684-958a00d6c986][Roam Research]], Cornell method, or the traditional [[roam:Linear notes]].

When doing something like this, one could take notes how to make their notes interesting to read.
One could start to [[id:d024516b-35ea-40ae-9433-ceacea695073][Write paragraphs like music]], create notes with [[id:79357d56-74bf-4854-820c-c0ad849f2468][Classic prose]], and [[id:b318dc2b-5fa1-48ff-9d33-6fbbdee46a2f][Write down the simplest possible example]].
