#+title: Classic prose
#+date: "2021-04-07 15:09:24 +08:00"
#+date_modified: "2021-04-22 15:02:06 +08:00"
#+language: en
#+tags: writing


Classic prose is a model of communication with the philosophy of using prose as a window onto the writer's world.

In order to make this model effective, the writer has to keep the guidelines in mind:

- The reader and writer are equals.
- Only shows the objective reality.
- Conversational.
- Focus on the subject, not the process of studying it.

This model of communication encourages a reader-centric focus on writing without looking down on them.
For example, with the saying "The people of America are getting fatter.", we both know means that the average of the population of America are getting fatter, not every single one of them.
Just like in a casual conversation, the reader has a rough idea of what they're reading.
They are reading to see what the writer has to do something about the subject.

The guideline of keeping it as objective as possible also encourages being concise.
You can [[file:2021-02-28-14-52-58.org][Create examples of ranking complexity when documenting your project serving as a abstract]].
It is written on equal footing with the reader, after all.
Thus, any writing suited to impress is a pointless addition (and can rub the wrong way for the reader).

Consequently, this [[file:2021-04-22-15-00-34.org][Reduce writing fluff]] that you often see in academic and legal writings.
