:PROPERTIES:
:ID:       c77d109a-4285-402e-aedd-2afa56301adf
:END:
#+title: Make a hub note to connect ideas together
#+date: "2021-05-07 22:46:41 +08:00"
#+date_modified: "2021-05-07 23:45:26 +08:00"
#+language: en


When initially writing your notes, you may find unrelated ideas hard to navigate.
For example, you have several notes with no related notes but are best described as different learning techniques.
The notes have no relation to each other so it doesn't make sense to link them.
Explicitly linking each note just to navigate between them misses the point of making associations.

In order of preference, there are several ways to get around this:

- Create a note outlining all of the smaller notes to a common topic.

- Depending if the notes themselves make up a single idea, combine them into a single note.

- [[id:c15325eb-4506-449c-b8dd-300801f53adc][A good tagging system for files for reducing information overload]].

As a side effect, writing a hub note enforces chunking of your notes.
Furthermore, it also [[id:92a10fe2-f4d1-4e5e-b5f4-3779db13a2e5][Create roadmaps to stay on track]] with the ability to select certain notes for a topic.
You get to explicitly define the topic instead of relying on backlinks or similar features.
