:PROPERTIES:
:ID:       c6cd9441-104f-447f-9d2c-9aaead388c22
:END:
#+title: When note-taking, don't satisfy your ego
#+date: "2021-04-26 18:59:30 +08:00"
#+date_modified: "2021-06-24 20:12:47 +08:00"
#+language: en


Note-taking are meant as a mental scratchpad, not some sort of creative writing.
The time you spent making things align as if you have OCD could be spent editing and improving other notes.

Personal notes, no matter how poorly written or unmaintained, are still valuable.
So if you have tendencies like this, just relax and correct them. :)
Trashing notes should be taken as a last resort if you're sure it is not relevant to you in the present and in the near future.
Still, you should keep in mind that [[id:3994e8d7-8d77-4f52-9650-330369e82143][Future-proofing your notes is only worth if the future is relevant]].

Found some inconsistent titles?
Improper metadata?
Incorrect datetime format?
Just correct them as you stumble upon them.

Other examples include:

- Satisfying my obsessiveness over the little things such as sorting lines for the note metadata in alphanumerical order.
- Finding the perfect note system and constantly shopping for better tools.
- Consequently from the previous point, obsessing over the fact that the first draft of my notes are not perfect.
- Collecting every resources for the future (see [[id:6b0e6b75-410f-42a3-8921-bcc4589b2d2a][Collecting information only feels like progress]]).

A similar dilemma I have yesterday is trying to format the metadata my Org mode files and sorting them alphabetically.
I've written a script and as I'm not experienced in text processing, I spent most of my time reading up documentation on the tools.
I did learned something with the tools but I've realized it's a big waste of time especially if my notes have grown.
If I found another hip and new note-taking method and it doesn't conform to the new ideal notes in my mind, then I should relax and try it out.
If it's good and I integrated it, I'll simply link it to my old notes.
