:PROPERTIES:
:ID:       c0e4fb0e-68f2-4db4-8c3e-f5a7845738c3
:END:
#+title: Understanding comes first from memory
#+date: "2021-05-14 11:48:20 +08:00"
#+date_modified: "2021-05-14 12:55:29 +08:00"
#+language: en


Rote learning is often considered to be an inferior method of understanding a concept.
It is often underestimated.
You may have often hear something along the lines of "I don't want to memorize a bunch of facts but rather understand the process." or "Knowing something is different from understanding something.";
rooted from an experience of bad teaching thus we associate memorizing a bunch of facts as bad.

Knowing the related things — or memorizing a bunch of facts — is a good way to understand a concept.
With those things in mind, you can then combine the ideas, [[id:1e135aee-0464-4756-9f55-bbf12afe8254][Chunking]] them, and innovate new ones.
You cannot build upon more ideas if you don't know what those ideas are.

- You cannot know how to read and write traditional music notation if you don't want to memorize the order of the notes or the meaning of various symbols.
  You can't put your finger why Undertale's music ties altogether with familiarity in its entire soundtrack or why [[https://www.youtube.com/watch?v=SdDeufxfJeE][Baka Mitai sounds very good]].

- Don't expect to have a good time comprehending derivatives if you don't know how to get the missing values from a system of equations or don't know what is a function.

From personal experience, I used to not like this rote method of learning.
After some reflection, I think I got the reason: lack of understanding especially with the basics.
Remember that [[id:114b7874-6a20-49c8-be2c-46970c7110dc][Information is only acquired when you try to make sense of it]].
The problem could be the lack of time understanding it.
