:PROPERTIES:
:ID:       d885e93b-f919-4338-a6b9-3438538e18c0
:END:
#+title: Every copy of the techniques is personalized
#+date: "2021-05-02 16:52:22 +08:00"
#+date_modified: "2021-05-14 13:01:31 +08:00"
#+language: en


Different people have different ways of understanding.
From every tips, tricks, and techniques that are echoed throughout the internet, the most effective technique will always end up that you optimized.
This is especially true for (primarily) solo activities such as [[id:0d2264a6-e487-4761-818a-d17d2833120f][Note-taking]] or learning a new hobby.
Whether you've been speedrunning a game, aiming to type 100 words per minute, composing an album, or illustrating a character, you are eventually taking the time to improve it.

An example of it is me hearing about the [[id:24b5e144-dda4-482c-9684-958a00d6c986][Roam Research]] from the trending page from Hacker News.
That's where I eventually found out about the [[id:4259636e-e0e8-49e4-8210-758ec59728a3][Zettelkasten]] method.
I began to like the method as I feel my traditional structured notes lack to become independent notes.
Then, I eventually found about org-roam and the rest is history (as of 2021-05-07).

Another example is [[https://zettelkasten.de/posts/use-case-investing-zettelkasten-method/][somebody has used Zettelkasten method in investing by using structure notes]].
It isn't stated by a Zettelkasten guide anywhere to use it like that but it did worked out for them.

When starting anew, you are curious on getting started.
You've read articles, watched videos, and practice the things you just learned.
You eventually came to like some of the things you think are cool, you integrated it to your own endeavor, and it is now a part of your workflow — e.g.,
you began to take speedrun with routes you're comfortable with, you start to optimize your reading while typing, you chose to compose with a modern version of Bach's workflow, you began to change how you make strokes with confidence.
Overall, [[id:05a39f96-fb1c-4d71-9be1-fc4c2e251e8f][Start small and improve later]] but always take the time to do [[id:9b669fd4-e04e-43dd-a61e-81dea5ec0764][Deliberate practice]] to prevent yourself getting stuck to one idea.
