:PROPERTIES:
:ID:       d885e93b-f919-4338-a6b9-3438538e18c0
:END:
#+title: Adapt out of self-interest
#+date: "2021-05-02 16:52:22 +08:00"
#+date_modified: "2021-05-04 20:52:15 +08:00"
#+language: en


In the age of internet containing lots of information, there can be only few that we can apply.
This is relevant in the various fields I watch such as programming, web development, and even learning: another programming language has arrived, a new web framework of the week, and a hip note-taking system is making its way for their spotlight.
It would be hypocritical to say I didn't take part of this.

If [[id:24b5e144-dda4-482c-9684-958a00d6c986][Roam Research]] hasn't took off, I wouldn't find out about org-roam and write this note in a [[id:4259636e-e0e8-49e4-8210-758ec59728a3][Zettelkasten]].
But the fact of the matter is this method makes a lot of sense to me as an extension of my already existing hierarchical notebook.
Instead of following arbitrary tips, evaluate if it's worth to you.
You are more adaptable than you think.
Every modern concept is basically standing on an established topic including programming languages, web frameworks, and learning methods.

When I first heard and use Roam Research (with org-roam), I used it exactly as it demonstrated and featured on various videos.
Over time, it makes more sense to me as an extension of my hierarchical notebook that can also be an independent network of notes.
The Zettelkasten is where the ideas and content from my hierarchical notebook end up as an atomic unit of knowledge.
It lets me take notes as normal and eventually improve upon them with the Zettelkasten.

Another example is [[https://zettelkasten.de/posts/use-case-investing-zettelkasten-method/][somebody has used Zettelkasten method in investing by using structure notes]].
It isn't stated by a Zettelkasten guide anywhere to use it like that but it did worked out for them.
