:PROPERTIES:
:ID:       9a11ef31-b2a7-43a9-a7a9-48f191838c6e
:END:
#+title: Prefer referencing over remembering
#+date: "2021-04-06 22:25:17 +08:00"
#+date_modified: "2021-05-09 18:08:32 +08:00"
#+language: en
#+tags: personal-info-management


It makes for less cognitive overhead.
This is especially true in the age of internet where information is widely distributed.
Even without the internet, however, it is still useful to find ways to refer to things.

This doesn't mean that you should avert remembering, that would be silly as little remembering is still required.
You're still trying to understand a concept, after all.
The gist of it is knowing the basics of a concept and its relations to others, enabling you to come up with a more effective search query.
If nothing else, you could take advantage of the help system insisted by the tool.

Examples:

- On a Unix-based environment, for example, has the manual pages with ~man~ and you can search through ~apropos~.
  This is especially needed if you're using BSD-based operating systems such as FreeBSD and OpenBSD.

- [[https://www.gnu.org/software/texinfo/][Texinfo]] and [[https://github.com/tldr-pages/tldr][tldr pages]].

- [[roam:Emacs][GNU Emacs]] has a great built-in help system.
  (See [[id:0efb9c51-3a12-4e5a-9e9b-d48cf4bd53ce][Using the built-in help system of Emacs]] for more details.)

If the system has a way of referencing something (other than the internet), use it to your advantage as you may find something valuable.
