#+title: Linguistics, style, and writing in the 21st century
#+date: "2020-11-14 22:07:13 +08:00"
#+date_modified: "2021-04-25 16:40:05 +08:00"
#+language: en
#+tags: media.talk writing
#+source: https://youtu.be/OV5J6BfToSw
#+author: Steven Pinker

# TODO: Give examples to several of the sections here.
#       It would be ironic if I didn't now, yes?

#+begin_abstract
This talk focuses on the problem of postmodernistic writings and how to avoid them.
It discusses the how this plague has started and proposes to look into writing from a more scientific perspective.
This note attempts to condense the 50-minute talk into several paragraphs.
#+end_abstract

Bad writing exists is a fact of life especially in bureaucrats, academics, corporates, and legal faculties.
Good people can write bad prose probably due to deliberate decisions, pseudo-intellectuals, and language (and stylistic) changes.

Some have theorized why this happened such as the degeneration of the language which happens at least one time per generation.
Others have concluded it might be due to writing being an unnatural act like baking, brewing, and crafting.




* Classic prose

Since writing is an unnatural act, we can make use of science to investigate what makes good writing.
One of the starting points of good writing is a good model of communication.

One of the more popular model is the [[file:../2021-04-07-15-09-24.org][Classic prose]].

- View the writing as the window of the world.
- Reader and writer as equals.
- The writer guides the reader into seeing the objective reality.
- Conversational.




* How does classic prose help?

Because it gives reader credit, it implies coordination between the reader and the writer.
Just like how you would intepret in a conversation, hearing "The students in this school are getting dumber." equates to the most students seem to be getting dumber.
It knows that the reader can read between the lines since they read to know how the writer will do about the subject.

Classic prose should serve the following goals:

- Make the reader sees a world instead of verbiage.
- Narrate the current events.
- Focus on the thing being shown instead of the activities that progressed it.

By consequence, classic style minimizes fluff such as:

- Apologizing (e.g., "as the concept of children is yet to be defined, more research is required").
- Hedge words (e.g., apparently, partially, a little bit, mostly).
- Metaconcepts (concepts about concepts) (e.g., approach, perspective, subjects).
- Professional narcissism (e.g., boasting about sales instead of the synopsis of the product, media outlets covering the stats of the coverage [popularity, reads, clicks, etc.] instead of the event itself).
- Cliches and idioms (e.g., piece of cake, ace in the hole).
- [[https://en.wikipedia.org/wiki/Scare_quotes][Shutter quotes]] (e.g., "in-the-know", "quick study").
- Zombie nouns (e.g., "make an appearance" instead of "appear", "creating a literary piece" instead of "writing").




* Why passive voice gets the blame?

It is often known that academics abuse the passive voice.
As a result, traditional manuals often include avoiding use of it.

But first, we have to know why passive voice are often used.

As the presenter reveals, it is stemmed from the limitations of the language and how bad writers write.

Language is a way of converting our web of thoughts into a linear string of words.
A web can freely overlap in concepts but a linear sentence cannot.
A sentence has to do two things: show the subject and its relation to other things and introduce bits of information that are relevant to the reader.
Often, this comes into the form of the doer then showing the actions and maybe its effect.

# TODO: Show an example on how English with only active voice is bad
#       and how passive voice is introduced as a solution.

Bad writers starts from what they know.
They focus on the effect, leaving the cause as an afterthought which makes it a use case for passive voice.
This causes the traditional manuals to discourage the use of passive voice.

But it does not mean that passive voice is inherently bad.
Passive voice offers a different way to order your thoughts.




* The curse of knowledge

#+begin_quote
Once you know something, it's hard to imagine from the perspective of a newcomer.
#+end_quote

The curse of knowledge — also known as hindsight bias, egocentrism, and mindblindness — is the tendency of the writer to not consider the background of the reader.
This often makes the writing filled with unexplained jargon, abbreviations, and references that the reader may not know.

For example, the writer may refer to a terminology a fellow expert may know or miss enlisting the definition of a jargon.

One of the well-known solutions to this problem is to be emphatic to your readers.
But as Pinker adds, we're not good at it since we don't know what our readers will like or not like.
The better solution is to give the draft to a real-life representative reader and gather as much feedback as possible.
You could make yourself as you would read the writing in the future.




* How language evolves

The evolution of the language changes the opinion of the writers.
As it turns out, some of the things deemed as ungrammatical by popular writers.

- Singular they.
- Split infinitive.
- Prepositions at the end of the sentence.
- Passive voice.

Several modern manuals also say that there is nothing wrong with the above things.
