:PROPERTIES:
:ID:       093b340a-3f5e-4a46-9017-f74b89caab13
:END:
#+title: Anki: Learning process
#+date: "2021-05-12 13:09:27 +08:00"
#+date_modified: "2021-05-12 13:30:08 +08:00"
#+language: en
#+property: anki_deck Learning process

The cards here are based from the course titled "Learning how to learn" taught by Barbara Oakley and Terence Sejnowski.




* Pitfalls and illusions of competence
:PROPERTIES:
:ANKI_DECK: Learning process
:ANKI_NOTE_TYPE: Styled cards
:END:
** Front
Give various pitfalls and illusions of competence to look out when learning.
** Back
- *The presence of the material itself* can cause students to foolishly think they already know about the subject.
- Similarly, *studying with solutions can be a trap if you focus on the what and how rather than the why*.
- Various common practices such as highlighting, rereading, and mind mapping are not as effective and only applicable in specific situations.
- The einstellung mindset, *being invested in an idea that you can't see other solutions*.
- Similarly, *overlearning can occur if you're aiming for complete mastery when you should move on after understanding the concept*.

* Practices for studying
:PROPERTIES:
:ANKI_NOTE_TYPE: Styled cards
:END:
** Front
Give various practices for studying effectively.
** Back
:PROPERTIES:
:ID:       85cd8ec5-c96c-496f-a748-5dd9d2c1136d
:END:
- *Recalling is one of the more effective practices compared to rereading or highlighting.*
  Self-testing is one of the better strategies, overall.

- *Prefer spaced repetition* over cramming as scientifically, the learning process takes some time to settle.

- *Get the key ideas ahead* and as you're studying, fill the details.
  This includes skimming — reading through the chapter, looking at the keywords.

- *Practice interleaving your studies* — that is, studying other subjects and/or moving to later topics as you understand the topic.

- *Focus, understand, and practice.*
  Learning can occur bottom-up (learning the details of a problem) and top-down (learning the bigger picture of a topic).
  Using both creates context and that's where you put your understanding to the test as you learn when to apply what you've learn.

- Use memory palace technique — that is, to *create analogies, narratives, and mnemonics*.
