:PROPERTIES:
:ID:       25fb4ebf-2cc4-40fe-93ad-37a79aedfb41
:END:
#+title: The basics of memory
#+date: 2021-05-02 23:05:42 +08:00
#+date_modified: 2021-07-20 17:57:59 +08:00
#+language: en


As for this note, we'll talk about the basics of memory neuroscientifically.




# TODO: Practices on improving memory
* Basic anatomy of the brain

Remebering from our basic biology lessons, we know that the brain contains *neurons that store information*.
These information can be connected together with *synapses that represents a web of thoughts* from the process of [[id:1e135aee-0464-4756-9f55-bbf12afe8254][Chunking]].
It shows why [[id:9f1f35dd-7cf9-4f47-a9a9-b647e5daa2af][We are more associative than structured]];
indeed, we are very skilled in linking and jumping between ideas.
You may have moments of suddenly remembering that you forgot to bring something while in the middle of your nap or a Eureka! moment where you suddenly understand why the quadratic formula makes sense.

The memory can be compared to the muscles as it strengthens the more you use and decays the more you neglect.
In order for this to work, however, you need to set some time for the neural structure to harden first.
This is why cramming doesn't work and [[id:063dfd73-dbf5-437b-b6f1-d7aeca196f31][Spaced repetition]] is often considered a better method.




* Working and long-term memory

Our brain has a lot of ideas and random thought that pass by each day, it also has a large space of information we can store to accommodate.
While we can categorize many parts of the memory, we'll focus with the two main parts:

- *The working memory contains all of the immediate information we have for the task at hand.*
  This is our mental scratchpad or our working desk containing all of the tools and materials needed for the project.

- *The long-term memory contains all of the information we know.*
  This is like our notebook, formally linking all of the information with each other.
  Continuing with the working desk analogy, this is our warehouse of our tools and materials.

With time, our memory consolidates, becoming more familiar with the concept.
This is when we get out of our beginner phase to a semi-expert.
When we retrieve a memory, it can be strengthened and even altered forming false memories.




* Focused and diffused mode

While there are many ways to describe the state of memory, we'll use two: focused and diffused mode.

- *Focused mode is when we intensely use our mental capacity to do a task.* — e.g., solving a math problem, completing a coding competition problem set, cooking a new meal, [[id:815b2beb-40a0-4e79-9097-5b688189ad5b][Writing]], [[id:cd7e8120-6953-44a6-9004-111f86ac52dc][Illustration]], [[id:0d2264a6-e487-4761-818a-d17d2833120f][Note-taking]].

- *Diffused mode is the relaxed state of our mind.*
  It often happens when we take a break, walk outside, and give in to guilty pleasures.

Despite the conception our brain is working whenever we focus, our brain is working all day.
