name: Generate site to GitHub pages
on:
  push:
    branches:
      - master
jobs:
  generate-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup for static site generation
        run: |
          nix-shell -p nodejs
          mv notebook/ site/public/
          cd site
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          jekyll: false
          target_branch: gh-pages
          build_dir: site/out
        env:
          GITHUB_TOKEN: ${{ secrets.PAGES_TOKEN }}

